CREATE DATABASE AI_PRODUCTIVITY;
USE AI_PRODUCTIVITY;

CREATE TABLE STUDENTS(
	NAME VARCHAR(50),
	STUDENT_ID INT PRIMARY KEY AUTO_INCREMENT,
	BRANCH VARCHAR(50)
);

CREATE TABLE STUDY_SESSIONS(
	SESSION_ID INT PRIMARY KEY AUTO_INCREMENT,
	STUDENT_ID INT,
    STUDY_DATE DATE,
    SUBJECT VARCHAR(50),
    STUDY_HOURS DECIMAL(4,2),
    DISTRACTION_COUNT INT,
    FOCUS_RATING INT CHECK(FOCUS_RATING BETWEEN 1 AND 10),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID)
);

CREATE TABLE SLEEP_DATA(
	SLEEP_ID INT PRIMARY KEY AUTO_INCREMENT,
    STUDENT_ID INT,
    SLEEP_DATE DATE,
    SLEEP_HOURS DECIMAL(4,2),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID)
);

CREATE TABLE TEST_SCORES(
	TEST_ID INT PRIMARY KEY AUTO_INCREMENT,
    STUDENT_ID INT,
    SUBJECT VARCHAR(50),
    SCORE INT,
    TEST_DATE DATE,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID)
);







